wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.13
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699205785.460976
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.7.13
      5: 0.15.4
      8:
      - 5
